<div class="w-prd-list-cell">
                  <div class="w-prd-list-cell-in">
                    <div class="w-prd-con">
                      <div class="w-prd-imgbox" title="[field:title/]"> <a href="[field:arcurl/]" class="img-count w-prd-img">
                        <div class="aspectRatio" style="padding-bottom:100%"></div>
                        <div class="img-count-in"><img alt="[field:title/]" src="[field:picname/]"/></div>
                        </a> </div>
                      <div class="w-prd-infobox"  style="text-align:left">
                        <h2 class="w-prd-name" title="[field:title/]"> <a href="[field:arcurl/]">[field:title/]</a> </h2>
                        <div class="w-prd-sum">[field:typename/]</div>
                      </div>
                    </div>
                  </div>
                </div>