<tr>
                              <td class="td-w" width="18.11514372872834%"><div class="div-padding">
                                  <div class="li-div">
                                    <div class="not-animated w-simImg" data-animate="fadeInUp" style="cursor:pointer;">
                                      <div class="image-w"> <a href="javascript:void(0);" >
                                        <div class="img"> <img src="[field:typeimg/]"/> </div>
                                        <div class="caption w-img-caption">
                                          <div class="captionbg"></div>
                                        </div>
                                        </a> </div>
                                    </div>
                                  </div>
                                </div></td>
                              <td class="td-w" width="81.88485627127166%"><div class="div-padding">
                                  <div class="li-div">
                                    <div class="not-animated w-text" data-animate="fadeInUp" style="">
                                      <div style="font-size:115%; margin-bottom:10px; font-weight:bold;">[field:typename/]</div>
                                      <div style="line-height:1.2;">[field:description/]</div>
                                    </div>
                                  </div>
                                </div></td>
                            </tr>