
                  <li>
                    <div class="lantern-item">
                      <div class="lantern-item-in"> <img class="g-cover" src="[field:typeimg/]" style=""/> <a href="javascript:void(0);" target="_self"><span id="2e3a64cf421f3b776220ef4336dc9bad" style="display:none;">none</span></a>
                        <div class="textbox" style="" >
                          <div class="textbox_mask"></div>
                          <div class="text">
                            <div class="text_in"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </li>
                  