<div class="li-div">
                                        <div class="not-animated w-simImg imgFloatFull textFade imgScaleSmall imgTextF" data-animate="fadeInUp" style="cursor:pointer;">
                                          <div class="image-w"> <a title="[field:typename/]" href="[field:typelink/]" >
                                            <div class="img"> <img src="[field:typeimg/]"/> </div>
                                            <div class="caption w-img-caption">
                                              <div class="captionbg"></div>
                                            </div>
                                            </a> </div>
                                        </div>
                                      </div>