<td class="td-w" width="50%"><div class="div-padding">
                                      <div class="li-div">
                                        <div class="not-animated w-simImg imgFloatFull textFade imgScaleSmall imgTextF" data-animate="fadeInUp" style="cursor:pointer;text-align:center;padding-bottom:10px;">
                                          <div class="image-w"> <a title="[field:title/]" href="[field:arcurl/]" >
                                            <div class="img"> <img src="[field:picname/]"/> </div>
                                            <div class="caption w-img-caption">
                                              <div class="captionbg"></div>
                                            </div>
                                            </a> </div>
                                        </div>
                                      </div>
                                      <div class="li-div">
                                        <div class="not-animated w-text" data-animate="fadeInUp" style="">
                                          <div style=" text-align:center;">
                                            <div style="color:#00BDCB;">[field:title/]</div>
                                            <div style="font-size:88%;">[field:description function="cn_substr(@me,50)"/]...</div>
                                          </div>
                                        </div>
                                      </div>
                                    </div></td>