<?php
$z[0]=Array("pubdate","",147,190);
$z[0][4]=array();
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",250,295);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y-m',@me)";
$z[2]=Array("arcurl","",432,447);
$z[2][4]=array();
$z[3]=Array("title","",456,470);
$z[3][4]=array();
$z[4]=Array("title","",473,487);
$z[4][4]=array();
$z[5]=Array("description","",546,596);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,400)";

?>