<?php
$z[0]=Array("field","",11,37);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",111,139);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",142,171);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n                    <li><a href =\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    ",441,596);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>