<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='active' \":@me=\"\";",622,713);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channelartlist","\r\n              <li class='{dede:field.currentstyle/}'>\r\n                <div class=\"li-parent-div li-parentOne-div\"><a href =\"{dede:field name='typeurl'/}\" >{dede:field name='typename'/}<i class=\"fa fa-plus\"></i></a></div>\r\n                <i class=\"nav_simpline_cur\"></i>\r\n                <div class=\"submenu\">\r\n                  <div class=\"back-div\"><i class=\"fa fa-angle-left\"></i><span>返回</span></div>\r\n                  <ul>\r\n                    {dede:channel type='son' noself='yes'}\r\n                    <li><a href =\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    {/dede:channel}\r\n                  </ul>\r\n                </div>\r\n              </li>\r\n              ",790,1566);
$z[1][4]=array();
$z[1][4]['typeid']="top";
$z[1][4]['currentstyle']="active";
$z[2]=Array("field","(@me==\"\")? @me=\" class='active' \":@me=\"\";",2669,2760);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channelartlist","\r\n            <li class='{dede:field.currentstyle/}'>\r\n              <div class=\"li-parent-div li-parentOne-div\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}<i class=\"fa fa-plus\"></i></a></div>\r\n              <i class=\"nav_simpline_cur\"></i>\r\n              <div class=\"submenu\">\r\n                <div class=\"back-div\"><i class=\"fa fa-angle-left\"></i><span>返回</span></div>\r\n                <ul>\r\n                  {dede:channel type='son' noself='yes'}\r\n                  <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                  {/dede:channel}\r\n                </ul>\r\n              </div>\r\n            </li>\r\n            ",2835,3582);
$z[3][4]=array();
$z[3][4]['typeid']="top";
$z[3][4]['currentstyle']="active";

?>